services:
  - type: web
    name: protolabs-platform
    env: node
    buildCommand: npm install --include=dev && npm run build
    startCommand: node server/index.cjs
    envVars:
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        value: hmore8655@gmail.com
      - key: ADMIN_PASSWORD
        value: PROTOLABS@123
      - key: MONGODB_URI
        value: mongodb+srv://protolabs26_db_user:nzPpm8XB6R687Ot3@cluster0.7hkrpyd.mongodb.net/protolabs_platform?retryWrites=true&w=majority&appName=Cluster0
